### PR TITLE
Add CI/CD

### PR DESCRIPTION
**Pull request by princedograAU**

### CODE REVIEW

**Comment by peter-high** [comment]
Can see files added. Don't see any impact

**Comment by mush** [comment]
> Can see files added. Don't see any impact

It'll probably have to be merged in the main branch.

**Comment by princedograAU** [comment]
@mush would it be `OK` to merge it to main?

**Review by mush — APPROVED** [review]

**Comment by mush** [comment]
> @mush would it be `OK` to merge it to main?

Go ahead with the merging if @peter-high is happy.

**Review by peter-high — APPROVED** [review]
Looks good to me

**Pull request merged**
